version: '3'
services:
  postgres:
    image: postgres:14
    container_name: java-postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=111'
      - 'POSTGRES_DB=Project2'
  app:
    build: ./
    container_name: java-app
    ports:
      - "9090:9090"





